### ISSUE TITLE
Create an Alert component

### ISSUE THREAD

**Issue by CuriousCoder00** [CuriousCoder00/percept-ui#1]
Create an alert component.
- Component should have a button-outside-click disbale
- Component should have a props passed to it as definining is component a modal popover or a notification alert
       -  If modal popover then should have a close button and give position props to set the modal position on the page
       -  If notification alert then it should disappear after a set amount of time or when user closes it with click on `X` button

> If you can give any additional feature, ou are welcome to do so
> Please provide screenshots in your PR

**Comment by rishang14** [comment]
can i work on this

**Comment by CuriousCoder00** [comment]
@rishang14  assigned to you!!! Kudos!
