### ISSUE TITLE
[docs]: Isuue in alignment of  Alert tab

### ISSUE THREAD

**Issue by rishang14** [CuriousCoder00/percept-ui#21]
### Summary

Due to position property of fixed  when i am providing alert with position while rendering in docs it is shown outside of the div 

![Screenshot 2024-09-24 215335](https://github.com/user-attachments/assets/65760cc1-9541-4c07-b175-49afb30cabe4)

### Issue Type

Documentation bug

### Steps to reproduce the issue

1. open our docs website 
2. go to alert tab 
3. see the issue

### If the issue is confirmed, would you be willing to submit a pull request?

Yes

**Comment by CuriousCoder00** [comment]
This issue is related to having the fixed property

**Comment by CuriousCoder00** [comment]
We can either remove this component.. as i believe user would only like to see alert component after an action has been taken from user not without action..
or we can create a trigger that would trigger the alert action and then it would work like a toast
